Typing compatible Channels
tbug/aiochannel pull request #14
Opened 2023-02-17 12:38 UTC by mosquito

Full typing compatibility for `Channel`

<img width="636" alt="image" src="https://user-images.githubusercontent.com/792981/219655480-f22c61bc-2673-4dc6-aef9-54fb612ffb56.png">

2023-02-17 12:41 UTC, mosquito commented
@tbug Do you want me to add py.typed and CI Actions for type checking etc.

2023-02-17 12:48 UTC, dizballanze approved these changes, later dismissed

2023-02-17 12:49 UTC, Alviner approved these changes, later dismissed

2023-02-17 13:16 UTC, leenr requested changes

2023-02-17 13:16 UTC, leenr commented on aiochannel/channel.py
> +    def __iter__(self) -> Iterable[T]:
```suggestion
    def __iter__(self) -> Iterator[T]:
```

2023-02-17 13:16 UTC, leenr commented on aiochannel/channel.py
> +from typing import Any, Generic, Iterable, TypeVar, Deque
```suggestion
from asyncio import AbstractEventLoop, Event, Future, get_event_loop
from typing import Any, Deque, Generic, Iterable, TypeVar
```

2023-02-17 13:16 UTC, leenr commented on aiochannel/channel.py
>      def _init(self):
```suggestion
    def _init(self) -> None:
```

2023-02-17 13:25 UTC, tudborg commented
Would be great @mosquito 👍

2023-02-17 13:31 UTC, mosquito commented
@tbug How do you look at modernizing this project a little, adding pyproject.toml and transferring all the project settings there. I think that it will be cleaner and easier than maintaining self-written scripts. 

<summmary>For example, now, a lot of superfluous gets into the sdist:
<details>

```
    $ python3.10 setup.py sdist
    running sdist
    running egg_info
    writing aiochannel.egg-info/PKG-INFO
    writing dependency_links to aiochannel.egg-info/dependency_links.txt
    writing top-level names to aiochannel.egg-info/top_level.txt
    reading manifest file 'aiochannel.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.md'
    writing manifest file 'aiochannel.egg-info/SOURCES.txt'
    running check
    creating aiochannel-1.1.1
    creating aiochannel-1.1.1/aiochannel
    creating aiochannel-1.1.1/aiochannel.egg-info
    creating aiochannel-1.1.1/tests
    creating aiochannel-1.1.1/tests/examples
    creating aiochannel-1.1.1/tests/regressions
    creating aiochannel-1.1.1/tools
    copying files to aiochannel-1.1.1...
    copying MANIFEST.in -> aiochannel-1.1.1
    copying README.rst -> aiochannel-1.1.1
    copying setup.cfg -> aiochannel-1.1.1
    copying setup.py -> aiochannel-1.1.1
--> copying tox.ini -> aiochannel-1.1.1**
    copying aiochannel/__init__.py -> aiochannel-1.1.1/aiochannel
    copying aiochannel/channel.py -> aiochannel-1.1.1/aiochannel
    copying aiochannel/errors.py -> aiochannel-1.1.1/aiochannel
    copying aiochannel/version.py -> aiochannel-1.1.1/aiochannel
    copying aiochannel.egg-info/PKG-INFO -> aiochannel-1.1.1/aiochannel.egg-info
    copying aiochannel.egg-info/SOURCES.txt -> aiochannel-1.1.1/aiochannel.egg-info
    copying aiochannel.egg-info/dependency_links.txt -> aiochannel-1.1.1/aiochannel.egg-info
    copying aiochannel.egg-info/not-zip-safe -> aiochannel-1.1.1/aiochannel.egg-info
    copying aiochannel.egg-info/top_level.txt -> aiochannel-1.1.1/aiochannel.egg-info
--> copying tests/__init__.py -> aiochannel-1.1.1/tests
--> copying tests/test_channel.py -> aiochannel-1.1.1/tests
--> copying tests/test_channel_35features.py -> aiochannel-1.1.1/tests
--> copying tests/examples/__init__.py -> aiochannel-1.1.1/tests/examples
--> copying tests/examples/consume_channel_python35.py -> aiochannel-1.1.1/tests/examples
--> copying tests/examples/simple_usage.py -> aiochannel-1.1.1/tests/examples
--> copying tests/regressions/__init__.py -> aiochannel-1.1.1/tests/regressions
--> copying tests/regressions/test_invalid_state_error_during_close.py -> aiochannel-1.1.1/tests/regressions
--> copying tools/clean.sh -> aiochannel-1.1.1/tools
--> copying tools/test-requirements.txt -> aiochannel-1.1.1/tools
    Writing aiochannel-1.1.1/setup.cfg
    Creating tar archive
    removing 'aiochannel-1.1.1' (and everything under it)
```

</details>
</summary>

2023-02-17 14:37 UTC, mosquito commented
@tbug a [modern project structure](https://github.com/mosquito/aiochannel/pull/1) awaiting your review

2023-02-17 19:31 UTC, tbug commented
@mosquito neat. Will take a look ASAP.

I haven't done python professionally for years, so I'm a little rusty 🙃

2023-02-18 09:40 UTC, tbug commented
Looks good @mosquito.

I've updated tox.ini so it should not be runnable with the current workers.

Please squash your commits down into 1 commit, then I'll merge it in.

2023-02-18 19:58 UTC, mosquito commented
@tbug it's already here.

2023-02-18 20:22 UTC, mosquito commented
@tbug I would ask you not to hurry with the release right away, maybe the other of my ideas will be included here.

2023-02-19 05:41 UTC, merged

2023-02-19 05:42 UTC, tbug commented
Sure thing @mosquito. We'll take a look at your other changes as well 👍

2023-02-19 14:00 UTC, tbug commented
`v1.2.0` released on PyPI